title: Cyber-Blog
description: "A blog where I post my learnings on the field"
author: 
  name: "DBR098"
  email: "dennybarreirorubio@hotmail.com"
  url: ""

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner: "DBR098"
year : "2022"
